apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\hiremata\RiderProjects\CloudStackCadenceIntegration\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cloudstackcadenceintegration
  name: cloudstackcadenceintegration
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloudstackcadenceintegration
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\hiremata\RiderProjects\CloudStackCadenceIntegration\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: cloudstackcadenceintegration
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          image: cloudstack-cadence-integration:latest
          name: cloudstackcadenceintegration
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
